export const code = {

    // SITE
    //Success
    requestEmailOtpSuccess: "REQUEST_EMAIL_OTP_SUCCESS",
    validateEmailConfirmationOtpSuccess: "VALIDATE_EMAIL_CONFIRMATION_OTP_SUCCESS",
    createCheckoutSuccess: "CREATE_CHECKOUT_SUCCESS",

    //Error
    requestEmailOtpError: "REQUEST_EMAIL_OTP_ERROR",
    validateEmailConfirmationOtpError: "VALIDATE_EMAIL_CONFIRMATION_OTP_ERROR",
    createCheckoutError: "CREATE_CHECKOUT_ERROR",

    // APP
    //Success
    loginSuccess: "LOGIN_SUCCESS",
    logoutSuccess: "LOGOUT_SUCCESS",
    takeoverSuccess: "TAKEOVER_SUCCESS",
    requestPwdResetSuccess: "REQUEST_PWD_RESET_SUCCESS",
    confirmPwdResetSuccess: "CONFIRM_PWD_RESET_SUCCESS",
    validatePwdResetHashSuccess: "VALIDATE_PWD_RESET_HASH_SUCCESS",
    requestWinbackSuccess: "REQUEST_WINBACK_SUCCESS",
    confirmWinbackSuccess: "CONFIRM_WINBACK_SUCCESS",
    validateWinbackHashSuccess: "VALIDATE_WINBACK_HASH_SUCCESS",
    restoreSubscriptionSuccess: "RESTORE_SUBSCRIPTION_SUCCESS",
    changeInvoiceEmailSuccess: "CHANGE_INVOICE_EMAIL_SUCCESS",
    //Error
    authInvalidCredentialsError: "AUTH_INVALID_CREDENTIALS_ERROR",
    authSessionConflictError: "AUTH_SESSION_CONFLICT_ERROR",
    authSessionExpiredError: "AUTH_SESSION_EXPIRED_ERROR",
    authSessionInvalidError: "AUTH_SESSION_INVALID_ERROR",
    requestPwdResetError: "REQUEST_PWD_RESET_ERROR",
    validatePwdResetHashError: "VALIDATE_PWD_RESET_HASH_ERROR",
    confirmPwdResetError: "CONFIRM_PWD_RESET_ERROR",
    requestWinbackError: "REQUEST_WINBACK_ERROR",
    validateWinbackHashError: "VALIDATE_WINBACK_HASH_ERROR",
    confirmWinbackError: "CONFIRM_WINBACK_ERROR",
    restoreSubscriptionError: "RESTORE_SUBSCRIPTION_ERROR",
    changeInvoiceEmailError: "CHANGE_INVOICE_EMAIL_ERROR",
    stripePriceRecurringError: "STRIPE_PRICE_RECURRING_ERROR",
    stripeCouponCurrencyNotFoundError: "STRIPE_COUPON_CURRENCY_NOT_FOUND_ERROR",
    externalRequestFailedError: "EXTERNAL_REQUEST_FAILED_ERROR",

    discountIdEmptyError: "DISCOUNT_ID_EMPTY_ERROR",
    discountPriceIdEmptyError: "DISCOUNT_PRICE_ID_EMPTY_ERROR",
    discountPriceIdInvalidError: "DISCOUNT_PRICE_ID_INVALID_ERROR",
    discountNameEmptyError: "DISCOUNT_NAME_EMPTY_ERROR",
    discountDurationEmptyError: "DISCOUNT_DURATION_EMPTY_ERROR",
    discountCountEmptyError: "DISCOUNT_COUNT_EMPTY_ERROR",
    discountCountNegativeError: "DISCOUNT_COUNT_NEGATIVE_ERROR",
    discountTypeEmptyError: "DISCOUNT_TYPE_EMPTY_ERROR",
    discountTypeInvalidError: "DISCOUNT_TYPE_INVALID_ERROR",
    discountPercentValueOutOfBoundsError: "DISCOUNT_PERCENT_VALUE_OUT_OF_BOUNDS_ERROR",
    discountDurationInvalidError: "DISCOUNT_DURATION_INVALID_ERROR",
    discountCountNotAllowedError: "DISCOUNT_COUNT_NOT_ALLOWED_ERROR",
    discountCampaignStartsAtEmptyError: "DISCOUNT_CAMPAIGN_STARTS_AT_EMPTY_ERROR",
    discountCampaignEndsAtEmptyError: "DISCOUNT_CAMPAIGN_ENDS_AT_EMPTY_ERROR",
    discountCampaignEndsAtInvalidError: "DISCOUNT_CAMPAIGN_ENDS_AT_INVALID_ERROR",
    discountValueNegativeError: "DISCOUNT_VALUE_NEGATIVE_ERROR",
    discountCycleRequiredError: "DISCOUNT_CYCLE_REQUIRED_ERROR",
    discountCycleInvalidError: "DISCOUNT_CYCLE_INVALID_ERROR",
    discountCycleNotAllowedError: "DISCOUNT_CYCLE_NOT_ALLOWED_ERROR",
    discountEndsAtInvalidError: "DISCOUNT_ENDS_AT_INVALID_ERROR",
    discountNotFoundError: "DISCOUNT_NOT_FOUND_ERROR",
    discountExternalIdEmptyError: "DISCOUNT_EXTERNAL_ID_EMPTY_ERROR",
    priceIdEmptyError: "PRICE_ID_EMPTY_ERROR",
    priceNotFoundError: "PRICE_NOT_FOUND_ERROR",
    pricePlanIdEmptyError: "PRICE_PLAN_ID_EMPTY_ERROR",
    pricePlanIdInvalidError: "PRICE_PLAN_ID_INVALID_ERROR",
    priceValueNegativeError: "PRICE_VALUE_NEGATIVE_ERROR",
    priceBillingCycleEmptyError: "PRICE_BILLING_CYCLE_EMPTY_ERROR",
    priceBillingCycleInvalidError: "PRICE_BILLING_CYCLE_INVALID_ERROR",
    priceExternalIdEmptyError: "PRICE_EXTERNAL_ID_EMPTY_ERROR",
    priceExternalIdNotFoundError: "PRICE_EXTERNAL_ID_NOT_FOUND_ERROR",

    // PRODUCT SUCCESS
    findAllPriceSuccess: "FIND_ALL_PRICE_SUCCESS",
    findByIdPriceSuccess: "FIND_BY_ID_PRICE_SUCCESS",
    createPriceSuccess: "CREATE_PRICE_SUCCESS",
    createBulkPriceSuccess: "CREATE_BULK_PRICE_SUCCESS",

    findAllPlanSuccess: "FIND_ALL_PLAN_SUCCESS",
    findByIdPlanSuccess: "FIND_BY_ID_PLAN_SUCCESS",
    createPlanSuccess: "CREATE_PLAN_SUCCESS",
    createBulkPlanSuccess: "CREATE_BULK_PLAN_SUCCESS",
    findAllDiscountSuccess: "FIND_ALL_DISCOUNT_SUCCESS",
    findAllByPriceIdDiscountSuccess: "FIND_ALL_BY_PRICE_ID_DISCOUNT_SUCCESS",
    findByIdDiscountSuccess: "FIND_BY_ID_DISCOUNT_SUCCESS",
    createDiscountSuccess: "CREATE_DISCOUNT_SUCCESS",
    deleteDiscountSuccess: "DELETE_DISCOUNT_SUCCESS",

    planNotFoundError: "PLAN_NOT_FOUND_ERROR",
    planIdEmptyError: "PLAN_ID_EMPTY_ERROR",
    planCreateError: "PLAN_CREATE_ERROR",
    planNameEmptyError: "PLAN_NAME_EMPTY_ERROR",
    planPricesEmptyError: "PLAN_PRICES_EMPTY_ERROR",
    planExternalIdNotFoundError: "PLAN_EXTERNAL_ID_NOT_FOUND_ERROR",

    moneyCurrencyMismatchError: "MONEY_CURRENCY_MISMATCH_ERROR",

    internalServerError: "INTERNAL_ERROR",
    unauthorized: "UNAUTHORIZED",
    forbidden: "FORBIDDEN",
    notFound: "NOT_FOUND",
    conflict: "CONFLICT",
    badRequest: "BAD_REQUEST",
};
