export const code = {

    // SITE
    //Success
    requestEmailOtpSuccess: "REQUEST_EMAIL_OTP_SUCCESS",
    validateEmailConfirmationOtpSuccess: "VALIDATE_EMAIL_CONFIRMATION_OTP_SUCCESS",
    createCheckoutSuccess: "CREATE_CHECKOUT_SUCCESS",

    //Error
    requestEmailOtpError: "REQUEST_EMAIL_OTP_ERROR",
    validateEmailConfirmationOtpError: "VALIDATE_EMAIL_CONFIRMATION_OTP_ERROR",
    createCheckoutError: "CREATE_CHECKOUT_ERROR",

    // APP
    //Success
    loginSuccess: "LOGIN_SUCCESS",
    logoutSuccess: "LOGOUT_SUCCESS",
    takeoverSuccess: "TAKEOVER_SUCCESS",
    requestPwdResetSuccess: "REQUEST_PWD_RESET_SUCCESS",
    confirmPwdResetSuccess: "CONFIRM_PWD_RESET_SUCCESS",
    validatePwdResetHashSuccess: "VALIDATE_PWD_RESET_HASH_SUCCESS",
    requestWinbackSuccess: "REQUEST_WINBACK_SUCCESS",
    confirmWinbackSuccess: "CONFIRM_WINBACK_SUCCESS",
    validateWinbackHashSuccess: "VALIDATE_WINBACK_HASH_SUCCESS",
    restoreSubscriptionSuccess: "RESTORE_SUBSCRIPTION_SUCCESS",
    changeInvoiceEmailSuccess: "CHANGE_INVOICE_EMAIL_SUCCESS",
    //Error
    authInvalidCredentialsError: "AUTH_INVALID_CREDENTIALS_ERROR",
    authSessionConflictError: "AUTH_SESSION_CONFLICT_ERROR",
    authSessionExpiredError: "AUTH_SESSION_EXPIRED_ERROR",
    authSessionInvalidError: "AUTH_SESSION_INVALID_ERROR",
    requestPwdResetError: "REQUEST_PWD_RESET_ERROR",
    validatePwdResetHashError: "VALIDATE_PWD_RESET_HASH_ERROR",
    confirmPwdResetError: "CONFIRM_PWD_RESET_ERROR",
    requestWinbackError: "REQUEST_WINBACK_ERROR",
    validateWinbackHashError: "VALIDATE_WINBACK_HASH_ERROR",
    confirmWinbackError: "CONFIRM_WINBACK_ERROR",
    restoreSubscriptionError: "RESTORE_SUBSCRIPTION_ERROR",
    changeInvoiceEmailError: "CHANGE_INVOICE_EMAIL_ERROR",


    featureNotFoundError: "FEATURE_NOT_FOUND_ERROR",
    featureNameEmptyError: "FEATURE_NAME_EMPTY_ERROR",
    featureIdEmptyError: "FEATURE_ID_EMPTY_ERROR",
    featureKeyEmptyError: "FEATURE_KEY_EMPTY_ERROR",
    featurePlanIdEmptyError: "FEATURE_PLAN_ID_EMPTY_ERROR",
    featurePlanIdInvalidError: "FEATURE_PLAN_ID_INVALID_ERROR",
    featureQuotaNotEnabledError: "FEATURE_QUOTA_NOT_ENABLEDS_ERROR",
    featureQuotaOutOfBoundsError: "FEATURE_QUOTA_OUT_OF_BOUNDS_ERROR",
    featureQuotaDisabledMustBeZeroError: "FEATURE_QUOTA_DISABLED_MUST_BE_ZERO_ERROR",
    featureOrderNegativeError: "FEATURE_ORDER_NEGATIVE_ERROR",
    featureDuplicatedKeyError: "FEATURE_DUPLICATED_KEY_ERROR",

    discountIdEmptyError: "DISCOUNT_ID_EMPTY_ERROR",
    discountPriceIdEmptyError: "DISCOUNT_PRICE_ID_EMPTY_ERROR",
    discountPriceIdInvalidError: "DISCOUNT_PRICE_ID_INVALID_ERROR",
    discountKeyEmptyError: "DISCOUNT_KEY_EMPTY_ERROR",
    discountNameEmptyError: "DISCOUNT_NAME_EMPTY_ERROR",
    discountDurationEmptyError: "DISCOUNT_DURATION_EMPTY_ERROR",
    discountCountEmptyError: "DISCOUNT_COUNT_EMPTY_ERROR",
    discountCountNegativeError: "DISCOUNT_COUNT_NEGATIVE_ERROR",
    discountTypeEmptyError: "DISCOUNT_TYPE_EMPTY_ERROR",
    discountTypeInvalidError: "DISCOUNT_TYPE_INVALID_ERROR",
    discountPercentValueOutOfBoundsError: "DISCOUNT_PERCENT_VALUE_OUT_OF_BOUNDS_ERROR",
    discountDurationInvalidError: "DISCOUNT_DURATION_INVALID_ERROR",
    discountCountNotAllowedError: "DISCOUNT_COUNT_NOT_ALLOWED_ERROR",
    discountCampaignStartsAtEmptyError: "DISCOUNT_CAMPAIGN_STARTS_AT_EMPTY_ERROR",
    discountCampaignEndsAtEmptyError: "DISCOUNT_CAMPAIGN_ENDS_AT_EMPTY_ERROR",
    discountCampaignEndsAtInvalidError: "DISCOUNT_CAMPAIGN_ENDS_AT_INVALID_ERROR",
    discountValueNegativeError: "DISCOUNT_VALUE_NEGATIVE_ERROR",
    discountCycleRequiredError: "DISCOUNT_CYCLE_REQUIRED_ERROR",
    discountCycleInvalidError: "DISCOUNT_CYCLE_INVALID_ERROR",
    discountCycleNotAllowedError: "DISCOUNT_CYCLE_NOT_ALLOWED_ERROR",
    discountEndsAtInvalidError: "DISCOUNT_ENDS_AT_INVALID_ERROR",
    discountNotFoundError: "DISCOUNT_NOT_FOUND_ERROR",
    discountExternalIdEmptyError: "DISCOUNT_EXTERNAL_ID_EMPTY_ERROR",
    discountDuplicatedKeyError: "DISCOUNT_DUPLICATED_KEY_ERROR",

    priceIdEmptyError: "PRICE_ID_EMPTY_ERROR",
    priceNotFoundError: "PRICE_NOT_FOUND_ERROR",
    pricePlanIdEmptyError: "PRICE_PLAN_ID_EMPTY_ERROR",
    pricePlanIdInvalidError: "PRICE_PLAN_ID_INVALID_ERROR",
    priceKeyEmptyError: "PRICE_KEY_EMPTY_ERROR",
    priceValueNegativeError: "PRICE_VALUE_NEGATIVE_ERROR",
    priceDuplicatedKeyError: "PRICE_DUPLICATED_KEY_ERROR",
    priceBillingCycleEmptyError: "PRICE_BILLING_CYCLE_EMPTY_ERROR",
    priceBillingCycleInvalidError: "PRICE_BILLING_CYCLE_INVALID_ERROR",
    priceExternalIdEmptyError: "PRICE_EXTERNAL_ID_EMPTY_ERROR",
    priceExternalIdNotFoundError: "PRICE_EXTERNAL_ID_NOT_FOUND_ERROR",

    planNotFoundError: "PLAN_NOT_FOUND_ERROR",
    planIdEmptyError: "PLAN_ID_EMPTY_ERROR",
    planCreateError: "PLAN_CREATE_ERROR",
    planNameEmptyError: "PLAN_NAME_EMPTY_ERROR",
    planKeyEmptyError: "PLAN_KEY_EMPTY_ERROR",
    planFeaturesEmptyError: "PLAN_FEATURES_EMPTY_ERROR",
    planPricesEmptyError: "PLAN_PRICES_EMPTY_ERROR",
    planExternalIdNotFoundError: "PLAN_EXTERNAL_ID_NOT_FOUND_ERROR",
    planDuplicatedKeyError: "PLAN_DUPLICATED_KEY_ERROR",

    moneyCurrencyMismatchError: "MONEY_CURRENCY_MISMATCH_ERROR",

    internalServerError: "INTERNAL_ERROR",
    unauthorized: "UNAUTHORIZED",
    forbidden: "FORBIDDEN",
    notFound: "NOT_FOUND",
    conflict: "CONFLICT",
    badRequest: "BAD_REQUEST",
};
